blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from app.views import *
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^shop/', include('shop.urls')),
                  # url(r'^shop/', include(('shop.urls', 'shop'), namespace='shop')),
                  url(r'^$', index, name='index'),
                  url(r'^about/$', about, name='about'),
                  url(r'^alist/$', alist, name='alist'),
                  url(r'^albums$', listpic, name='listpic'),
                  url(r'^search/$', search, name='search'),
                  url(r'^message$', message, name='message'),
                  url(r'^article/(P?\d+)$', article, name='article'),
                  url(r'^comment/$', comment, name='comment'),
                  url(r"^reg/$", reg),
                  url(r"^logout/$", dologout),
                  url(r"^tj/$", tj),
                  url(r"^catg/$", catg),
                  url(r'^grade/$', grade, name='grade'),
                  url(r'^login/$', checkin, name='checkin'),
                  url(r'^down/$', down, name='down'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.conf import settings
from django.db.models import Q

import re


class MsgsForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "输入昵称", "required": "required", }),
                           max_length=150, error_messages={"required": "昵称不能为空", })
    text = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "输入留言", "required": "required", }),
                           max_length=500, error_messages={"required": "留言不能为空", })


class UserForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=30)
    age = forms.CharField(max_length=30)
# class CommentForm(forms.Form):
#     '''
#     评论表单
#     '''
#     author = forms.CharField(widget=forms.TextInput(attrs={"id": "author", "class": "comment_input",
#                                                            "required": "required","size": "25", "tabindex": "1"}),
#                               max_length=50,error_messages={"required":"username不能为空",})
#     email = forms.EmailField(widget=forms.TextInput(attrs={"id":"email","type":"email","class": "comment_input",
#                                                            "required":"required","size":"25", "tabindex":"2"}),
#                                  max_length=50, error_messages={"required":"email不能为空",})
#     url = forms.URLField(widget=forms.TextInput(attrs={"id":"url","type":"url","class": "comment_input",
#                                                        "size":"25", "tabindex":"3"}),
#                               max_length=100, required=False)
#     comment = forms.CharField(widget=forms.Textarea(attrs={"id":"comment","class": "message_input",
#                                                            "required": "required", "cols": "25",
#                                                            "rows": "5", "tabindex": "4"}),
#                                                     error_messages={"required":"评论不能为空",})
#     article = forms.CharField(widget=forms.HiddenInput())

templates/about.html
<script src="https://www.chartjs.org/dist/2.7.3/Chart.bundle.js"></script>


<div class="topnews">


    <h2>年龄</h2>

    <div style="width:600px">
        <canvas id="myChart" width="600px" height="300px"></canvas>
    </div>
    <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {

                labels: {{x|safe}},
                datasets: [{
                    label: '年龄',
                    data: {{y}},
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>

templates/ages.html
<script src="https://www.chartjs.org/dist/2.7.3/Chart.bundle.js"></script>


<div class="topnews">


    <h2>年龄</h2>

    <div style="display: flex; align-items: center; justify-content: center; height: 100vh;">
        <canvas id="myChart" width="600px" height="300px"></canvas>
    </div>
    <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {

                labels: {{x|safe}},
                datasets: [{
                    label: '年龄',
                    data: {{y}},
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>

templates/alist.html
{% extends 'base.html' %}
{% block custom_css %}
    <link href="/static/css/main.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="con_content">
            <div class="about_box">
                <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a> >> <a href="/alist" target="_blank">文章</a></span><b></b>
                </h2>

                <div class="dtxw box">

                    {% for a in article_list %}
                        <li>
                            <div class="dttext f_l">
                                <ul>
                                    <h2><a href="/article/{{ a.id }}">{{ a.title }}</a></h2>
                                    <p>{{ a.text |safe | slice:":50" }}....</p>
                                    <span>{{ a.publish_time }}</span>
                                </ul>
                            </div>
                            <div class="xwpic f_r"><a href="/"><img src="/media/{{ a.header_img }}"></a></div>
                        </li>
                    {% endfor %}


                </div>


            </div>
        </div>

        <!-- container代码 结束 -->
{% endblock %}

templates/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>博客之家</title>
    <meta name="keywords" content="博客之家"/>
    <meta name="description" content="博客之家"/>
    <link href="/static/css/base.css" rel="stylesheet">
    {% block custom_css %}{% endblock %}
{#     # 在模块定义块#}
    <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
</head>
<body>
<div class="topnav">
    <a href="/" target="_blank">博客之家</a>――作品来自张勇     {% if request.user.is_authenticated %}
    <a  target="_blank">欢迎您，{{ request.user.username }}</a>{% endif %}
</div>
<div id="wrapper">
    <header>
        <div class="headtop"></div>
        <div class="contenttop">
            <div class="logo f_l">博客之家</div>
            <div class="search f_r">
                <form action="/search/" method="post" name="searchform" id="searchform">
                    <input name="keys" id="keyboard" class="input_text" value="请输入关键字"
                           style="color: rgb(153, 153, 153);"
                           onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}"
                           onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
                    {% csrf_token %}
                    <input name="Submit" class="input_submit" value="搜索" type="submit">
                </form>
            </div>
            <div class="blank"></div>
            <nav>
                <div class="navigation">
                    <ul class="menu">
                        <li><a href="/">网站首页</a></li>
						<li><a href="/albums">相册</a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="/message">留言</a></li>
                            <li><a href="/tj/">统计</a></li>
							<li><a href="/alist">全部文章</a></li>
		                    <li><a href="/shop/">商城</a></li>
                            <li><a href="/logout/">注销</a></li>
                        {% else %}
                            <li><a href="/login/">登陆</a></li>
                            <li><a href="/reg/">注册</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <SCRIPT type=text/javascript>
                // Navigation Menu
                $(function () {
                    $(".menu ul").css({display: "none"}); // Opera Fix
                    $(".menu li").hover(function () {
                        $(this).find('ul:first').css({visibility: "visible", display: "none"}).slideDown("normal");
                    }, function () {
                        $(this).find('ul:first').css({visibility: "hidden"});
                    });
                });
            </SCRIPT>
        </div>
    </header>
    {% block content %}{% endblock %}
    <footer>
        <div class="footer">
            <div class="f_l">
                <p>All Rights Reserved 版权所有：<a href="/">博客之家</a> 备案号：豫ICP备081217105号</p>
            </div>
            <div class="f_r textr">
                <p>Design by KJF</p>
            </div>
        </div>
    </footer>
</div>
</body>
</html>
 

templates/grade.html
{% extends 'base.html' %}
{% block custom_css %}
<link href="static/css/main.css" rel="stylesheet">
{% endblock %}
{% block content %}
  <div class="container">
    <div class="con_content">
      <div class="about_box">
        <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">信息浏览</a></span><b>成绩单</b></h2>
        <div class="f_box">
          <p class="a_title">个人成绩单</p>
          <p class="p_title"></p>
          <!--  <p class="box_p"><span>发布时间：2017-07-07 15:12:42</span><span>作者：唐孝文</span><span>来源：稽查支队</span><span>点击：111056</span></p>--> 
          <!-- 可用于内容模板 --> 
        </div>
        <ul class="about_content">
          <!-- <p> </p> -->
        <table class="bordered">
            <thead><tr>
                      <th>学年</th> 
                      <th>学期</th> 
                      <th>课程</th>
                      <th>学分</th> 
                      <th>绩点</th>
                      <th>成绩</th>   
            </tr></thead> 
            <tbody>
            {% for m in gd %}
            <tr> 
                         <td>{{m.year}}</td> 
                          <td>{{m.term}}</td> 
                          <td>{{m.title}}</td> 
                          <td>{{m.point}}</td> 
                          <td>{{m.gpa}}</td> 
                          <td>{{m.mark}}</td> 
           </tr> 
           {% endfor %}
           </tbody>
        </table>
       
        </ul>
      </div>
    </div>
    <style type="text/css">
table {    
*border-collapse: collapse; /* IE7 and lower */    
border-spacing: 0;    
width: 100%;    
}    
.bordered {    
border: solid #ccc 1px;    
-moz-border-radius: 6px;    
-webkit-border-radius: 6px;    
border-radius: 6px;    
-webkit-box-shadow: 0 1px 1px #ccc;    
-moz-box-shadow: 0 1px 1px #ccc;    
box-shadow: 0 1px 1px #ccc;    
}    
    
.bordered tr:hover {    
background: #fbf8e9;    
-o-transition: all 0.1s ease-in-out;    
-webkit-transition: all 0.1s ease-in-out;    
-moz-transition: all 0.1s ease-in-out;    
-ms-transition: all 0.1s ease-in-out;    
transition: all 0.1s ease-in-out;    
}    
    
.bordered td, .bordered th {    
border-left: 1px solid #ccc;    
border-top: 1px solid #ccc;    
padding:3px;/*供修改*/  
text-align: center;/*供修改*/    
}    
    
.bordered th {    
background-color: #dce9f9;    
background-image: -webkit-gradient(linear, left top, left bottom, from(#ebf3fc), to(#dce9f9));    
background-image: -webkit-linear-gradient(top, #ebf3fc, #dce9f9);    
background-image: -moz-linear-gradient(top, #ebf3fc, #dce9f9);    
background-image: -ms-linear-gradient(top, #ebf3fc, #dce9f9);    
background-image: -o-linear-gradient(top, #ebf3fc, #dce9f9);    
background-image: linear-gradient(top, #ebf3fc, #dce9f9);    
-webkit-box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;    
-moz-box-shadow:0 1px 0 rgba(255,255,255,.8) inset;    
box-shadow: 0 1px 0 rgba(255,255,255,.8) inset;    
border-top: none;    
text-shadow: 0 1px 0 rgba(255,255,255,.5);    
}    
    
.bordered td:first-child, .bordered th:first-child {    
border-left: none;    
}    
    
.bordered th:first-child {    
-moz-border-radius: 6px 0 0 0;    
-webkit-border-radius: 6px 0 0 0;    
border-radius: 6px 0 0 0;    
}    
    
.bordered th:last-child {    
-moz-border-radius: 0 6px 0 0;    
-webkit-border-radius: 0 6px 0 0;    
border-radius: 0 6px 0 0;    
}    
    
.bordered th:only-child{    
-moz-border-radius: 6px 6px 0 0;    
-webkit-border-radius: 6px 6px 0 0;    
border-radius: 6px 6px 0 0;    
}    
    
.bordered tr:last-child td:first-child {    
-moz-border-radius: 0 0 0 6px;    
-webkit-border-radius: 0 0 0 6px;    
border-radius: 0 0 0 6px;    
}    
    
.bordered tr:last-child td:last-child {    
-moz-border-radius: 0 0 6px 0;    
-webkit-border-radius: 0 0 6px 0;    
border-radius: 0 0 6px 0;    
}    
    </style>
  </div>
  <!-- container代码 结束 -->
  
{% endblock %}

templates/index.html
{% extends 'base.html' %} 
<!-- # 对父模板中进行扩展 -->
{% block custom_css %}
<link href="/static/css/index.css" rel="stylesheet">
{% endblock %} 
<!-- # 以上对父模板中同名进行重写 -->
{% block content %} 
<!-- # 将所用博客标题列表显示出来 -->
  <div class="jztop"></div>
  <div class="container">
    <div class="bloglist f_l">

     {% for article in article_list %}
      <h3><a href="/article/{{article.id}}">{{ article.title}}</a></h3> 
	  <!-- # {{ article.title}} 获得到一篇博客的title字段的值  article是实例对象 -->
      <figure> <img src="/media/{{article.header_img}}"></figure>
      <ul>
        <p> {{ article.text |safe| slice:":150"}} ......</p>
        <a title="" href="/article/{{article.id}}" target="_blank" class="readmore">阅读全文&gt;&gt;</a>
      </ul>
      <p class="dateview"><span>{{ article.publish_time}}</span><span>分类：{{ article.cate.name}}</span><span>作者：张勇</span><span>浏览次数：{{ article.browse_count}}</span></p>
     {% endfor %}

  <div class="pagelist">
<br><br>
  第{{page}}页&emsp;<a href="/">首页</a>

   {% if article_list.has_previous %}
      <a href="?page={{page | add:"-1"}}">上一页</a>
    {% else %}
    
   {% endif %}

 {% if article_list.has_next %}
      <a href="?page={{page | add:"1"}}">下一页</a>
    {% else %}
     
    {% endif %}
    </div>
    </div>


    <div class="r_box f_r">
      <div class="tit01">
        <h3 class="tit">关注我</h3>
        <div class="gzwm">
          <ul>
            <li><a class="email" href="#" target="_blank">我的电话</a></li>
            <li><a class="qq" href="https://mail.qq.com/" target="_blank">我的邮箱</a></li>
            <li><a class="tel" href="E:\Program Files\Tencent\QQ\Bin\QQScLauncher.exe" target="_blank">我的QQ</a></li>
            <li><a class="prize" href="/grade">个人奖项</a></li>
          </ul>
        </div>
      </div>
      <!--tit01 end-->
      <div class="tuwen">
        <h3 class="tit">音乐欣赏</h3>
 <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=300 height=400 src="http://music.163.com/outchain/player?type=0&id=44454257&auto=0&height=430"></iframe>     
        </div>
      <div class="tuwen">
        <h3 class="tit">图文推荐</h3>
        <ul>
        {% for h in hot %}

         <li><a href="/"><img src="/media/{{h.header_img}}"><b>{{ h.title | slice:":20"}}...</b></a>
            <p><span class="tulanmu"><a href="/alist">主要文章</a></span><span class="tutime">{{ h.publish_time}}</span></p>
          </li>

         {% endfor %}
        </ul>
      </div>

      <div class="ph">
        <!-- <h3 class="tit">点击排行</h3> -->
        <!-- <ul class="rank"> -->
          <!-- <li><a href="" title="" target="_blank"></a> -->
<!-- 		  <ol>
			{%for article_list in most_viewed %}
			<li>
				<a href="{{article_list.get_url_path}}">{{ article_list.title}}</a>
			</li>
			{% endfor%}
			</ol> -->
        </ul>
      </div>
      <div class="ad"> <img src="/static/images/03.jpg"> </div>
    </div>
  </div>
  <!-- container代码 结束 -->
  <div class="jzend"></div>
{% endblock %}

templates/listpic.html
{% extends 'base.html' %}
{% block custom_css %}
    <link href="static/css/main.css" rel="stylesheet">
    <link href="static/css/jquery.fs.boxer.css" rel="stylesheet">
    <style>
        .baguetteBox {
            width: 900px;
            margin: 0 auto;
            font-size: 0;
        }

        .baguetteBox img {
            display: inline-block;
            width: 215px;
            height: 150px;
            padding: 5px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="con_content">
            <div class="about_box">
                <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">相册</a></span><b>相册</b>
                </h2>

                <div class="lispic">
                    <ul>
                        {% for item in album %}
                            <li><a href="{{ item.path.url }}" class="boxer "><img
                                    src="{{ item.path.url }}"><span>{{ item.title }}</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div><div class="pagelist"><a href="/">首页</a></div>
<!--             页次：1/1 每页25 总数10<a href="/">上一页</a><a href="/">下一页</a><a
                    href="/">尾页</a> -->
        </div>

        <div class="blank"></div>
        <script src="static/js/jquery.fs.boxer.min.js"></script>
        <script type="text/javascript"> $('.boxer').boxer();
        </script>
    </div>
    <!-- container代码 结束 -->

{% endblock %}

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="用户登录">
    <meta name="author" content="">
    <title>用户登录</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css">
</head>


<body class="text-center">
<!-- 用于显示当前表单地址，即调用视图函数所对应的URL -->
<form class="form-signin" action="/shop/loggin/" method="post"> 
    <img class="mb-4" src="../media/01.jpg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">用户登录</h1>
    <label for="inputEmail" class="sr-only">用户名</label>
	<br>
    <input type="username" name="username" id="inputEmail" class="form-control" placeholder="用户名" required autofocus>
	</br>
    <label for="inputPassword" class="sr-only">密码</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="密码" required>
    {% csrf_token %}  <!-- 用于验证 -->
    <div class="checkbox mb-3 text-left">
        <label>
            <input type="checkbox" value="remember-me"> 记住我
        </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
	<span>没有账号？</span>  <a class="outer-link" href="/reg/">马上注册</a>
</form>
<style type="text/css">
    html, body {
        height: 100%;
    }

    body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: 0 auto;
    }

    .form-signin .checkbox {
        font-weight: 400;
    }

    .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
    }

    .form-signin .form-control:focus {
        z-index: 2;
    }

    .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }

    .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
</style>
</body>
</html>

templates/message.html
{% extends 'base.html' %}
{% block custom_css %}
    <link href="static/css/main.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="con_content">
            <div class="about_box">
                <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">信息浏览</a></span><b>留言墙</b>
                </h2>
                <div class="f_box">
                    <div class="com">
                        <form action="/message" method="post">
                            {% csrf_token %}
                            <p>输入你的昵称：<input type="text" name="name"> <span style="color:red;">{{ info }}</span></p><br>
                            <textarea name="msg" class="lj" cols="72" rows="11"> </textarea>
                            <br> <br>
                            <button class="btn" type="submit">给我留言</button>
                        </form>
                    </div>

                    <div class="m_list">
                        <ul>
                            {% for msg in msgs %}

                                <li class="entry">
                                    <div class="re_info"> {{ msg.name }} &emsp;{{ msg.publish_time }} </div>
                                    <br> {{ msg.text }} </li>

                            {% endfor %}
                        </ul>
                    </div>


                </div>

                <!-- container代码 结束 -->
            </div>
        </div>

    </div>
    <style type="text/css"> .com {
        margin: 0 auto;
        max-height: 400px;
        padding: 90px 80px;
        background-image: url("/static/images/bg.png");
        background-repeat: no-repeat;
    }

    .lj {
        font-size: 20px;
        margin: 0 auto;
        padding: 10px 10px;
    }

    .btn {
        background: #606c76;
        background: -webkit-linear-gradient(#606c76, #444444);
        background: linear-gradient(#606c76, #444444);
        border-radius: 6px;
        padding: 8px 20px;
        color: #ffffff;
        display: block;
        font: normal 400 24px/1 "Calibri", sans-serif;
        text-align: center;
        align: center;
        margin: 0 auto;
        text-shadow: 1px 1px #000000;
    }

    .m_list {
        font-size: 14px;
        padding-left: 80px;
        padding-top: 50px;
    }

    .entry {
        width: 728px;
        padding-bottom: 5px;
        border-top: 1px #fff solid;
        border-bottom: 1px #ddd dotted;
    }

    .re_info {
        padding: 10px 0 0 0;
        font-size: 12px;
        color: #888
    } </style>
    <!-- container代码 结束 -->
{% endblock %}

templates/model_list.html
#{% extends "admin/change_list.html" %}

#{% block filters %}
<div>
    <h6>文件上传:</h6>
    <form enctype="multipart/form-data" action="add/" method="post" id="staticfile_form">
            #{% csrf_token %}
            <label for="id_name">名称:</label>
            <input class="vTextField" id="id_name" maxlength="40" name="name" type="text" />
            <label for="id_url" class="required">URL:</label>
            <input id="id_url" name="url" type="file" />
            <input type="submit" value="保存" name="_save" />
    </form>
</div>
<br/>
<br/>

#{{ super }}
#{% endblock %}

templates/page.html
{% extends 'base.html' %}
{% block custom_css %}
    <link href="/static/css/main.css" rel="stylesheet">{% endblock %}
{% block content %}
    <div class="container">
        <div class="con_content">
            <div class="about_box">
                <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">信息浏览</a></span><b>博客文章</b>
                </h2>
                <div class="f_box">
                    <p class="a_title">{{ article.title }}</p>
                    <p class="p_title"></p>
                    <p class="box_p">
                        <span>发布时间：{{ article.publish_time }}</span><span>作者：张勇</span><span>点击：{{ article.browse_count }}</span>
                    </p>
                </div>
                <ul class="about_content">
                    <p> {{ article.text | safe }}</p>
                </ul>
                <div class="post_comment">
                    <h3 id="post_comment">发表评论</h3>
                    <div class="add_comm">
                        <textarea name="txtBody" id="commentContent" cols="60" rows="5" class="ipt-txt"
                                  placeholder="有您参与评论更精彩！" style=""></textarea>
                        <div class="comm_login" id="commentLoginPanel">
                            <span id="info" style="color:red;"></span>
                            <span class="p1">用户昵称</span>
                            <input type="text" placeholder="昵称" class="inpt rm_name" id="entered_UsernameInput">
                            {% csrf_token %}
                            <input type="button" value="发表" onclick="post_comm();" class="rm_smt" id="btn_loginbtn">
                        </div>
                    </div>
                    <h3>全部评论</h3>
                    <div id="divcommentlist">
                        <ul class="list" id="ulcommentlist">
                            {% for cm in cms %}
                                <li class="entry">
                                    <div class="re_info">{{ cm.name }} {{ cm.publish_time }}</div>
                                    &emsp;&emsp;{{ cm.text }}</li>
                            {% endfor %}
                    </div>

                </div>
                <!-- container代码 结束 -->
            </div>
        </div>
        <div class="blank"></div>
    </div>
    <!-- container代码 结束 -->
    <style type="text/css">.post_comment h3 {
        position: relative;
        margin: 10px 0 0 0;
        padding: 10px 0;
        font-size: 14px;
        font-weight: 700;
        color: #333333;
        border-bottom: 3px #333333 solid
    }

    .post_comment {
        font-size: 14px;
        font-family: 'Microsoft Yahei';
    }

    .add_comm {
        position: relative;
        height: 120px;
        border: 1px #ccc solid;
        border-top-width: 0;
        background: #fafafa
    }

    .add_comm textarea {
        position: absolute;
        left: 15px;
        top: 10px;
        height: 120px;
        border: 0;
        resize: none;
        outline: 0;
        font-size: 14px;
        line-height: 22px;
        background: 0 0;
    }

    .comm_login {
        position: absolute;
        left: 610px;
        bottom: 10px;
        width: 680px;
        padding: 0 10px
    }

    .comm_login input.inpt {
        width: 140px;
        height: 27px;
        line-height: 27px;
        padding: 0 5px;
        border: 1px #e9e9e9 solid;
        border-bottom: 1px #ccc solid;
        outline: 0
    }

    .comm_login input.rm_smt {
        width: 51px;
        height: 27px;
        border: 0;
        color: #fff;
        background: #056ebb;
        cursor: pointer
    }

    .comm_login span.p1 {
        padding: 0 5px 0 0
    }

    .entry {
        width: 728px;
        padding-bottom: 5px;
        border-top: 1px #fff solid;
        border-bottom: 1px #ddd dotted;
    }

    .re_info {
        padding: 10px 0 0 0;
        font-size: 12px;
        color: #888
    }

    #info {
        position: absolute;
        left: -160px;
    }
    </style>
    <script type="text/javascript">function post_comm() {
        var text = $("#commentContent").val();
        var name = $("#entered_UsernameInput").val();
        var csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val();
        $.post("/comment/", {
            name: name,
            comment: text,
            csrfmiddlewaretoken: csrfmiddlewaretoken,
            a_id:{{ article.id }}
        }, function (result) {
            var obj = JSON.parse(result);
            $("#info").html(obj.info);
            $("#ulcommentlist").append('<li class="entry"> <div class="re_info">' + name + ' 2018-1-20</div> &emsp;&emsp;' + text + '</li>');
        });
    }
    </script>
{% endblock %}